source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'BrickMan' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'Masonry', '~> 0.6.3'
    pod 'YYModel'
    pod 'SDWebImage'
end
